# 練習問題： かけ算の九九の表を2次元配列として作成する

## コード1

In [1]:
# NumPyをインポート
import numpy as np 

# 1から9までの連続した整数値の1次元配列aを作成
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# 1から9までの連続した整数値の1次元配列bを作成
b = np.arange(1, 10)

# bを9行x1列の2次元配列に変換
b = b.reshape(9,1)

# 以下のような行列のかけ算を行うことで
# 9行x9列の2次元配列(九九の表)が作成される
c = a * b

# cを表示
print(c)

[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]


## コード2

In [2]:
# NumPyをインポート
import numpy as np 

# 9行x9列の2次元配列を作成
d = np.ndarray((9,9))

# dは要素がfloat64型の配列であるため
# 整数のint8型の配列に変換
d = d.astype(np.int8)

# 2重ループで九九の表を作成
for i in range(9):
    for j in range(9):
        d[i][j] = (i + 1) * (j + 1)

print(d)

[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]
